# Generated by Django 4.2.3 on 2024-04-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frutas',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='verduras',
            options={'verbose_name_plural': 'Verduras'},
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='dtEntrega',
            new_name='data_prevista_entrega',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='endrNtrg',
            new_name='local_de_entrega',
        ),
        migrations.RenameField(
            model_name='entrega',
            old_name='nmClnt',
            new_name='nome_cliente',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='qntdDspnvl',
            new_name='estoque_disponivel',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='nmeFrt',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='frutas',
            old_name='prcFrt',
            new_name='preco_por_unidade_produto',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='entrega',
            new_name='entrega_do_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nmItm',
            new_name='nome_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='prcUnit',
            new_name='preco_unitario_do_item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='qntdd',
            new_name='quantidade_item',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='mtPgto',
            new_name='forma_de_pagamento',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='vlrTotal',
            new_name='valor_geral',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='stkVxL',
            new_name='estoque_disponivel',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='nmVdx',
            new_name='nome_produto',
        ),
        migrations.RenameField(
            model_name='verduras',
            old_name='pXcVdX',
            new_name='preco_por_unidade_produto',
        ),
    ]
